[package]
name = "ai"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sim-campaign = { path = "../sim-campaign" }
sim-battle = { path = "../sim-battle" }
data-model = { path = "../data-model" }
rayon.workspace = true

[dev-dependencies]
data-model = { path = "../data-model", features = ["test-support"] }
serde.workspace = true
serde_json.workspace = true
