//! Loads the real `data/` directory of the repository.

use std::path::PathBuf;

use data_model::{GameData, SocialClass};

fn data_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../data")
}

#[test]
fn real_data_loads_without_errors() {
    let (data, warnings) = GameData::load(&data_root()).expect("data/ must load");

    for warning in &warnings {
        println!("warning: {warning}");
    }
    println!(
        "loaded {} factions, {} provinces, {} unit types, {} buildings, {} technologies, {} characters, {} resources, {} religions, {} traits, {} skills, {} name lists, {} province polygons",
        data.factions.len(),
        data.provinces.len(),
        data.unit_types.len(),
        data.buildings.len(),
        data.technologies.len(),
        data.characters.len(),
        data.resources.len(),
        data.religions.len(),
        data.traits.len(),
        data.skills.len(),
        data.names.len(),
        data.province_geometry.len(),
    );

    assert!(!data.factions.is_empty());
    assert!(!data.unit_types.is_empty());
    assert!(!data.buildings.is_empty());
    assert!(!data.technologies.is_empty());
    assert!(!data.characters.is_empty());
    assert!(!data.resources.is_empty());
    assert!(!data.religions.is_empty());
    assert!(!data.traits.is_empty());
    assert!(!data.skills.is_empty());
    assert!(!data.names.is_empty());

    // Every branch of the skill tree must be represented, and every skill's
    // prerequisites already resolved as part of `GameData::load`.
    for branch in [
        data_model::SkillBranch::Command,
        data_model::SkillBranch::Governance,
        data_model::SkillBranch::Court,
    ] {
        assert!(
            data.skills
                .values()
                .any(|skill| skill.branch as u8 == branch as u8),
            "no skill in branch {branch:?}"
        );
    }

    // M6: two technology trees of ~15 nodes each, every tech dated, and at
    // least three buildings producing research points.
    for branch in [
        data_model::TechBranch::Military,
        data_model::TechBranch::Civil,
    ] {
        let count = data
            .technologies
            .values()
            .filter(|tech| tech.branch == branch)
            .count();
        assert!(count >= 14, "only {count} technologies in {branch:?}");
    }
    assert!(data.technologies.len() >= 30);
    for tech in data.technologies.values() {
        assert!(
            tech.historical_year
                .as_ref()
                .and_then(|y| y.year())
                .is_some(),
            "{} has no historical_year",
            tech.id
        );
        assert!(!tech.sources.is_empty(), "{} has no sources", tech.id);
    }
    let research_buildings = data
        .buildings
        .values()
        .filter(|b| {
            b.effects
                .iter()
                .any(|e| e.effect == data_model::EffectKind::ResearchPoints)
        })
        .count();
    assert!(research_buildings >= 3);
    assert!(data.buildings.contains_key("bld_scriptorium"));

    // The province folder is being regenerated by the geo pipeline; only the
    // presence of the anchor province is asserted, and province-related
    // warnings are tolerated.
    let normandie = data
        .provinces
        .get("prov_normandie")
        .expect("prov_normandie must exist");
    assert_eq!(normandie.owner.as_str(), "fac_france");
    assert!(
        normandie
            .population
            .classes
            .get(SocialClass::Peasants)
            .count
            > 0
    );

    let france = &data.factions["fac_france"];
    assert!(france.playable);
    assert_eq!(france.heraldry.primary_color, "#1F3A93");

    let non_province_warnings: Vec<_> = warnings
        .iter()
        .filter(|warning| !warning.message.contains("province"))
        .collect();
    assert!(
        non_province_warnings.is_empty(),
        "unexpected warnings: {non_province_warnings:?}"
    );
}
