"""Every data file is valid against its JSON schema (one table, one parametrised test)."""

from pathlib import Path

import pytest
from conftest import DATA, assert_matches_schema

# schema (in data/schemas/) -> data files or globs (relative to data/) that must match it.
SCHEMA_TABLE: dict[str, tuple[str, ...]] = {
    "agent_rules.schema.json": ("rules/agents.json",),
    "ai_alignment.schema.json": ("ai/alignment.json",),
    "ai_diplomacy.schema.json": ("ai/diplomacy.json",),
    "ai_doctrine.schema.json": ("ai/doctrines.json",),
    "ai_feudal.schema.json": ("ai/feudal.json",),
    "ai_grid.schema.json": ("ai/grid.json",),
    "ai_turn_replay.schema.json": ("ui/ai_turn_replay.json",),
    "army_rules.schema.json": ("rules/armies.json",),
    "army_traditions_rules.schema.json": ("rules/army_traditions.json",),
    "art_battle_grass.schema.json": ("art/battle_grass.json",),
    "art_battle_tree_leaves.schema.json": ("art/battle_tree_leaves.json",),
    "art_building_materials.schema.json": ("art/building_materials.json",),
    "art_building_regions.schema.json": ("art/building_regions.json",),
    "art_ga3_decor.schema.json": ("art/ga3_decor.json",),
    "art_tree_species.schema.json": ("art/tree_species.json",),
    "auto_resolve_rules.schema.json": ("rules/auto_resolve.json",),
    "battle_ability.schema.json": ("battle_abilities/*.json",),
    "battle_alerts_rules.schema.json": ("rules/battle_alerts.json",),
    "battle_crest_defence_rules.schema.json": ("rules/battle_crest_defence.json",),
    "battle_crest_rules.schema.json": ("rules/battle_crest.json",),
    "battle_decision_rules.schema.json": ("rules/battle_decision.json",),
    "battle_decor_plan.schema.json": ("battle_maps/decor_plan_example.json",),
    "battle_decor_rules.schema.json": ("rules/battle_decor.json",),
    "battle_demos.schema.json": ("ui/battle_demos.json",),
    "battle_duel_rules.schema.json": ("rules/battle_duel.json",),
    "battle_finish.schema.json": ("fx/battle_finish.json",),
    "battle_gore.schema.json": ("fx/battle_gore.json",),
    "battle_history_rules.schema.json": ("rules/battle_history.json",),
    "battle_horse_wait_rules.schema.json": ("rules/battle_horse_wait.json",),
    "battle_hover_rules.schema.json": ("rules/battle_hover.json",),
    "battle_layers.schema.json": ("audio/battle_layers.json",),
    "battle_map.schema.json": (
        "battle_maps/azincourt.json",
        "battle_maps/crecy.json",
        "battle_maps/poitiers.json",
    ),
    "battle_opening_rules.schema.json": ("rules/battle_opening.json",),
    "battle_order.schema.json": ("battle_orders/*.json",),
    "battle_outcome_rules.schema.json": ("rules/battle_outcome.json",),
    "battle_pace_rules.schema.json": ("rules/battle_pace.json",),
    "battle_prologue.schema.json": ("tutorial/battle_prologue.json",),
    "battle_push_rules.schema.json": ("rules/battle_push.json",),
    "battle_queue_rules.schema.json": ("rules/battle_queue.json",),
    "battle_replay_rules.schema.json": ("rules/battle_replay.json",),
    "battle_rout_rules.schema.json": ("rules/battle_rout.json",),
    "battle_scale_rules.schema.json": ("rules/battle_scale.json",),
    "battle_speeches.schema.json": ("speeches/battle_speeches.json",),
    "battle_standard_rules.schema.json": ("rules/battle_standards.json",),
    "battle_standards_fx.schema.json": ("fx/battle_standards.json",),
    "battle_time_of_day_rules.schema.json": ("rules/battle_time_of_day.json",),
    "battle_water_rules.schema.json": ("rules/battle_water.json",),
    "building.schema.json": ("buildings/*.json",),
    "building_models.schema.json": ("map/building_models.json",),
    "camera_feel.schema.json": ("ui/camera_feel.json",),
    "campaign_map_ui.schema.json": ("ui/campaign_map.json",),
    "campaign_seasons_ui.schema.json": ("ui/campaign_seasons.json",),
    "campaign_weather_rules.schema.json": ("rules/campaign_weather.json",),
    "capture_rules.schema.json": ("rules/capture.json",),
    "chivalric_order.schema.json": ("chivalric_orders/*.json",),
    "coast_types.schema.json": ("map/coast_types.json",),
    "crossings.schema.json": ("map/crossings.json",),
    "crusade_rules.schema.json": ("rules/crusade.json",),
    "custom_battle_rules.schema.json": ("rules/custom_battle.json",),
    "detail_zones.schema.json": ("map/detail_zones.json",),
    "difficulty_rules.schema.json": ("rules/difficulty.json",),
    "diplomacy_rules.schema.json": ("rules/diplomacy.json",),
    "economy_rules.schema.json": ("rules/economy.json",),
    "encounter.schema.json": ("encounters/*.json",),
    "encounter_rules.schema.json": ("rules/encounters.json",),
    "entity_icons.schema.json": ("ui/entity_icons.json",),
    "event.schema.json": ("events/*.json",),
    "faction.schema.json": ("factions/*.json",),
    "faction_borders.schema.json": ("map/faction_borders.json",),
    "feudal_rules.schema.json": ("rules/feudal.json",),
    "fine_anchors.schema.json": ("map/fine_anchors.json",),
    "forced_sea_edges.schema.json": ("map/forced_sea_edges.json",),
    "forest_cover.schema.json": ("map/forest_cover.json",),
    "formation_width_rules.schema.json": ("rules/formation_width.json",),
    "front_end.schema.json": ("ui/front_end.json",),
    "fx_atmosphere.schema.json": ("fx/atmosphere.json",),
    "fx_battle_animation.schema.json": ("fx/battle_animation.json",),
    "fx_battle_ground.schema.json": ("fx/battle_ground.json",),
    "fx_battle_ground_layers.schema.json": ("fx/battle_ground_layers.json",),
    "fx_battle_staging.schema.json": ("fx/battle_staging.json",),
    "fx_campaign_lighting.schema.json": ("fx/campaign_lighting.json",),
    "fx_campaign_terrain_textures.schema.json": ("fx/campaign_terrain_textures.json",),
    "fx_fa3_anim_sources.schema.json": ("fx/fa3_anim_sources.json",),
    "fx_fire_flipbooks.schema.json": ("fx/fire_flipbooks.json",),
    "fx_horizon.schema.json": ("fx/horizon.json",),
    "fx_siege_fire.schema.json": ("fx/siege_fire.json",),
    "fx_water_detail.schema.json": ("fx/water_detail.json",),
    "ground_biome_mix.schema.json": ("art/ground_biome_mix.json",),
    "group_formations.schema.json": ("rules/group_formations.json",),
    "heraldry_charges.schema.json": ("heraldry/charges/charges.json",),
    "heraldry_houses.schema.json": ("heraldry/houses.json",),
    "historical_forests.schema.json": ("map/historical_forests.json",),
    "historical_hydro_notes.schema.json": ("map/historical_hydro_notes.json",),
    "historical_lakes.schema.json": ("map/historical_lakes.json",),
    "icons_ink.schema.json": ("ui/icons_ink.json",),
    "illustrations.schema.json": ("ui/illustrations.json",),
    "lakes.schema.json": ("map/lakes.json",),
    "landmark.schema.json": ("landmarks/*.json",),
    "landmark_v2.schema.json": ("landmarks_v2/*.json",),
    "map_legend.schema.json": ("ui/map_legend.json",),
    "map_parchment_ornaments.schema.json": ("map/parchment_ornaments.json",),
    "map_scenes_rules.schema.json": ("rules/map_scenes.json",),
    "mercenary_rules.schema.json": ("rules/mercenaries.json",),
    "missile_arc_rules.schema.json": ("rules/missile_arc.json",),
    "missile_morale_rules.schema.json": ("rules/missile_morale.json",),
    "missions.schema.json": ("missions.json",),
    "modern_reservoirs.schema.json": ("map/modern_reservoirs.json",),
    "movement_rules.schema.json": ("movement/rules.json",),
    "music.schema.json": ("audio/music.json",),
    "naval_fleets.schema.json": ("naval/fleets.json",),
    "naval_rules.schema.json": ("naval/rules.json",),
    "naval_scenario.schema.json": ("naval/scenarios/*.json",),
    "naval_ship_names.schema.json": ("naval/ship_names.json",),
    "next_hints.schema.json": ("ui/next_hints.json",),
    "population_rules.schema.json": ("rules/population.json",),
    "portrait_archetypes.schema.json": ("portraits/archetypes.json",),
    "posture_rules.schema.json": ("rules/postures.json",),
    "province.schema.json": ("provinces/*.json",),
    "relief_pyramid.schema.json": ("map/relief_pyramid.json",),
    "replenishment_rules.schema.json": ("rules/replenishment.json",),
    "retinue.schema.json": ("retinue.json",),
    "river_crossings_rules.schema.json": ("rules/river_crossings.json",),
    "river_display.schema.json": ("map/river_display.json",),
    "river_names.schema.json": ("map/river_names.json",),
    "river_styles.schema.json": ("map/river_styles.json",),
    "river_widths.schema.json": ("map/river_widths.json",),
    "rivers_fine.schema.json": ("map/rivers_fine.json",),
    "sea_basins.schema.json": ("map/sea_basins.json",),
    "sea_lanes.schema.json": ("naval/sea_lanes.json",),
    "settlement.schema.json": ("settlements/prov_*.json",),
    "settlement_markers.schema.json": ("map/settlement_markers.json",),
    "settlement_rules.schema.json": ("settlements/rules.json",),
    "ship_class.schema.json": ("naval/ships/*.json",),
    "siege_capture_rules.schema.json": ("rules/siege_capture.json",),
    "siege_engine_rules.schema.json": ("rules/siege_engines.json",),
    "siege_engines.schema.json": ("fx/siege_engines.json",),
    "siege_fire_rules.schema.json": ("rules/siege_fire.json",),
    "siege_fx.schema.json": ("fx/siege_fx.json",),
    "siege_town_rules.schema.json": ("rules/siege_town.json",),
    "siege_works_rules.schema.json": ("rules/siege_works.json",),
    "sound_bank.schema.json": ("audio/sound_bank.json",),
    "stance_cues.schema.json": ("map/stance_cues.json",),
    "stance_fill.schema.json": ("map/stance_fill.json",),
    "starting_armies.schema.json": ("rules/starting_armies.json",),
    "title.schema.json": ("titles/*.json",),
    "tooltip_style.schema.json": ("ui/tooltip_style.json",),
    "tooltips.schema.json": ("ui/tooltips.json",),
    "town_footprint_rules.schema.json": ("rules/town_footprint.json",),
    "town_maquettes.schema.json": ("art/town_maquettes.json",),
    "towns_1340.schema.json": ("map/towns_1340.json",),
    "trade.schema.json": ("economy/trade.json",),
    "ui_fa_assets.schema.json": ("ui/fa_ui_assets.json",),
    "unit_formations_rules.schema.json": ("rules/unit_formations.json",),
    "unit_looks.schema.json": ("fx/unit_looks.json",),
    "unit_modes_rules.schema.json": ("rules/unit_modes.json",),
    "vision_rules.schema.json": ("rules/vision.json",),
    "voice_advisor.schema.json": ("voice/advisor.json",),
    "voice_barks.schema.json": ("voice/barks.json",),
    "voice_speech.schema.json": ("voice/speech_voices.json",),
    "war_scars_ui.schema.json": ("ui/war_scars.json",),
    "wetlands.schema.json": ("map/wetlands.json",),
}


def _cases() -> list:
    cases = []
    for schema_name, patterns in SCHEMA_TABLE.items():
        for pattern in patterns:
            paths = sorted(DATA.glob(pattern))
            assert paths, f"{pattern}: no data file"
            cases.extend(
                pytest.param(schema_name, path, id=path.relative_to(DATA).as_posix())
                for path in paths
            )
    return cases


@pytest.mark.parametrize(("schema_name", "data_path"), _cases())
def test_data_matches_schema(schema_name: str, data_path: Path) -> None:
    """The data file validates against its schema, with sibling `$ref`s resolved."""
    assert_matches_schema(data_path, schema_name)
