"""Validates data/settlements/*.json (lot C1, docs/design/2026-09-24-echelle-colonies.md § 3.1).

Each `<province_id>.json` file (every file but `rules.json`) must match
`settlement.schema.json` and the cross-file rules below. The folder may hold
no province file yet: provinces without one get a city generated by the Rust
loader from `capital_city`, which is not a file and is not checked here.
"""

import json
from collections import Counter
from pathlib import Path

import pytest

from cent_ans_tools.geo.project import default_grid

DATA = Path(__file__).resolve().parents[2] / "data"
SETTLEMENTS = DATA / "settlements"
RULES_FILE = "rules.json"

MIN_PER_FILE = 3
MAX_PER_FILE = 16
# The map square is wider than the requested lon/lat extent (docs/geo.md),
# so bounds are checked in map pixels, not degrees.
GRID = default_grid()


def _settlement_files() -> list[Path]:
    """Province settlement files, sorted; empty when none has been written yet."""
    if not SETTLEMENTS.is_dir():
        return []
    return sorted(
        path for path in SETTLEMENTS.glob("*.json") if path.name != RULES_FILE
    )


def _ids(folder: str) -> set[str]:
    """Entity ids of a data folder (file stems)."""
    return {path.stem for path in (DATA / folder).glob("*.json")}


def _load(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


SETTLEMENT_FILES = _settlement_files()


@pytest.mark.parametrize("path", SETTLEMENT_FILES, ids=lambda path: path.stem)
def test_settlement_file_is_valid(path: Path) -> None:
    """Schema, count, single named city, references and coordinates."""
    settlements = _load(path)

    province_path = DATA / "provinces" / f"{path.stem}.json"
    assert province_path.is_file(), f"{path.name}: unknown province {path.stem}"
    province = json.loads(province_path.read_text(encoding="utf-8"))

    assert MIN_PER_FILE <= len(settlements) <= MAX_PER_FILE, (
        f"{path.name}: {len(settlements)} settlements, expected "
        f"{MIN_PER_FILE}-{MAX_PER_FILE}"
    )
    cities = [s for s in settlements if s["kind"] == "city"]
    assert len(cities) == 1, f"{path.name}: {len(cities)} cities, expected 1"
    capital = province["capital_city"]["name"]["display"]
    assert cities[0]["name"]["display"] == capital, (
        f"{path.name}: city {cities[0]['name']['display']!r} "
        f"is not capital_city {capital!r}"
    )

    buildings = _ids("buildings")
    factions = _ids("factions")
    for settlement in settlements:
        label = f"{path.name}#{settlement['id']}"
        assert settlement["province"] == path.stem, f"{label}: province"
        unknown = set(settlement.get("buildings", [])) - buildings
        assert not unknown, f"{label}: unknown buildings {sorted(unknown)}"
        owner = settlement.get("owner")
        assert owner is None or owner in factions, f"{label}: unknown owner {owner}"
        lon, lat = settlement["lonlat"]
        column, row = GRID.lonlat_to_pixel(lon, lat)
        assert 0 <= column < GRID.width_px and 0 <= row < GRID.height_px, (
            f"{label}: {lon}, {lat} off the map"
        )


def test_settlement_ids_are_globally_unique() -> None:
    """No id appears twice across all province files (passes when none exists)."""
    counts = Counter(
        settlement["id"] for path in SETTLEMENT_FILES for settlement in _load(path)
    )
    duplicates = sorted(sid for sid, count in counts.items() if count > 1)
    assert not duplicates, f"duplicate settlement ids: {duplicates}"


def test_rules_file_matches_its_schema() -> None:
    """`rules.json` is valid and names existing unit types."""
    rules = json.loads((SETTLEMENTS / RULES_FILE).read_text(encoding="utf-8"))
    unit_types = _ids("unit_types")
    for kind, units in rules["starting_garrison"].items():
        unknown = set(units) - unit_types
        assert not unknown, f"starting_garrison.{kind}: unknown {sorted(unknown)}"
