"""HB2 (ADR 0143): ground materials of the campaign map generated by fal.ai.

Chain, driven by ``data/art/ground_materials.yaml``:

1. ``generate``: one nadir aerial orthophoto per material (``fal-ai/flux-2-pro`` 1024²,
   0.03 $/Mpx, catalogue price 2026-09-30) into ``~/dev/cent-ans-raw/hb/materials/``
   (``<id>_<attempt>.png``, never paid twice; every call logged in ``costs.json``).
2. ``seamless``: half-tile offset, then the two seam bands are replaced by min-error cuts
   (quilting-style dynamic programming) through copies that are continuous across each seam;
   large-scale lighting is flattened (wrap-around blur) so no blotch repeats at tile scale;
   mean linear luminance equalised to ``target_luminance`` (the colour map gives the hue);
   normal + roughness derived from the high-passed luminance (estimated height).
3. ``pack``: two grid images imported by Godot as ``CompressedTexture2DArray``
   (``hb_ground_albedo_array.jpg``, ``hb_ground_normal_array.jpg``: R, G = OpenGL normal X, Y,
   B = roughness, as ``terrain_normal_array.jpg``) + manifest
   ``data/art/ground_materials_pack.json`` (id -> layer, mean linear albedo).
4. ``board``: local review sheet, each texture tiled 2 x 2 (outside the repository).

Run: ``uv run --project tools --with fal-client cent-ans assets ground-materials generate``.
"""

from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path
from typing import Any

import numpy as np
import yaml
from jsonschema import Draft202012Validator
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import gaussian_filter

ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = ROOT / "data" / "art" / "ground_materials.yaml"
SCHEMA_PATH = ROOT / "data" / "schemas" / "ground_materials.schema.json"
MANIFEST_PATH = ROOT / "data" / "art" / "ground_materials_pack.json"
TEXTURE_DIR = ROOT / "game" / "assets" / "textures" / "terrain"
ALBEDO_NAME = "hb_ground_albedo_array.jpg"
NORMAL_NAME = "hb_ground_normal_array.jpg"
RES_DIR = "res://assets/textures/terrain/"
RAW_DIR = Path.home() / "dev" / "cent-ans-raw" / "hb" / "materials"

# Catalogue prices (USD per megapixel), fal pricing API 2026-09-30.
PRICES = {"fal-ai/flux-2-pro": 0.03, "fal-ai/flux-2": 0.012}
# Repository budget of the two arrays (spec: <= 40 MB).
MAX_PACK_BYTES = 40_000_000
ALBEDO_QUALITY = 88
NORMAL_QUALITY = 90
# Rec. 709 luma weights (linear RGB).
_LUMA = np.array([0.2126, 0.7152, 0.0722])
# Base roughness per role (matte crops, slightly glossier rock).
ROLE_ROUGHNESS = {"crop": 0.9, "canopy": 0.85, "ground": 0.8}
DEFAULT_HEIGHT_STRENGTH = 2.0


# ------------------------------------------------------------------ catalogue
def load_catalog(path: Path = CATALOG_PATH) -> dict[str, Any]:
    """Catalogue validated against its schema; layers must be 0..n-1 in order."""
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    errors = list(Draft202012Validator(schema).iter_errors(document))
    if errors:
        raise ValueError(f"{path.name} invalide : {errors[0].message}")
    ids = [m["id"] for m in document["materials"]]
    if len(ids) != len(set(ids)):
        raise ValueError("identifiants de matière en double")
    layers = [m["layer"] for m in document["materials"]]
    if layers != list(range(len(layers))):
        raise ValueError(f"couches non contiguës dans l'ordre : {layers}")
    return document


def build_prompt(
    document: dict[str, Any], entry: dict[str, Any], attempt: int = 1
) -> str:
    """Full prompt of ``entry`` (retry prompt for attempts >= 2 when given)."""
    body = entry["prompt"]
    if attempt >= 2 and entry.get("prompt_retry"):
        body = entry["prompt_retry"]
    scale = document["scale_sentence"].format(tile_m=entry["tile_m"])
    return " ".join(
        part.strip()
        for part in (document["style_prefix"], scale, body, document["style_suffix"])
        if part
    )


def raw_path(entry: dict[str, Any], attempt: int, raw_dir: Path = RAW_DIR) -> Path:
    """Raw generated image of ``entry`` for ``attempt``."""
    return raw_dir / f"{entry['id']}_{attempt}.png"


def call_cost(document: dict[str, Any]) -> float:
    """Catalogue cost of one generation (USD)."""
    megapixels = document["size"] * document["size"] / 1_000_000
    return round(PRICES[document["model"]] * megapixels, 4)


def select(document: dict[str, Any], only: list[str] | None) -> list[dict[str, Any]]:
    """Materials of the catalogue, restricted to ``only`` when given."""
    materials = document["materials"]
    if not only:
        return materials
    unknown = set(only) - {m["id"] for m in materials}
    if unknown:
        raise ValueError(f"matières inconnues : {sorted(unknown)}")
    return [m for m in materials if m["id"] in only]


# ------------------------------------------------------------------ generation
def generate(
    document: dict[str, Any],
    only: list[str] | None = None,
    attempt: int | None = None,
    dry_run: bool = False,
    raw_dir: Path = RAW_DIR,
) -> dict[str, Any]:
    """Generate the missing raw images; returns ``{"planned": [...], "cost": usd}``.

    ``attempt`` None = the attempt kept by the catalogue (``attempt``, default 1).
    Attempt ``n`` uses seed ``seed + 1000 * (n - 1)``.
    """
    planned = []
    for entry in select(document, only):
        number = attempt or entry.get("attempt", 1)
        target = raw_path(entry, number, raw_dir)
        if not target.exists():
            planned.append((entry, number, target))
    unit = call_cost(document)
    report = {
        "planned": [f"{e['id']}_{n}" for e, n, _ in planned],
        "cost": round(unit * len(planned), 4),
    }
    if dry_run or not planned:
        return report
    import fal_client  # only needed for paid calls

    raw_dir.mkdir(parents=True, exist_ok=True)
    log_path = raw_dir / "costs.json"
    log = json.loads(log_path.read_text()) if log_path.exists() else []
    for entry, number, target in planned:
        arguments = {
            "prompt": build_prompt(document, entry, number),
            "image_size": {"width": document["size"], "height": document["size"]},
            "seed": entry["seed"] + 1000 * (number - 1),
            "output_format": "png",
            "safety_tolerance": "5",
        }
        result = fal_client.subscribe(document["model"], arguments=arguments)
        urllib.request.urlretrieve(result["images"][0]["url"], target)
        (raw_dir / f"{target.stem}.json").write_text(
            json.dumps({"arguments": arguments, "result": result}, indent=1)
        )
        log.append(
            {
                "id": entry["id"],
                "attempt": number,
                "model": document["model"],
                "usd": unit,
                "time": time.strftime("%Y-%m-%dT%H:%M:%S"),
            }
        )
        log_path.write_text(json.dumps(log, indent=1))
        print(f"HB2 {target.name} ({unit} $)")
    return report


# ------------------------------------------------------------------ seamless
def _srgb_to_linear(values: np.ndarray) -> np.ndarray:
    return np.where(
        values <= 0.04045, values / 12.92, ((values + 0.055) / 1.055) ** 2.4
    )


def _linear_to_srgb(values: np.ndarray) -> np.ndarray:
    values = np.clip(values, 0.0, 1.0)
    return np.where(
        values <= 0.0031308, values * 12.92, 1.055 * values ** (1 / 2.4) - 0.055
    )


def _loop_cut(error: np.ndarray) -> np.ndarray:
    """Minimum-error path through ``error`` (rows x cols), one column per row.

    Steps of at most one column between rows; the path starts and ends on the same
    column (the best one of the first row) so it closes when the image wraps.
    """
    rows, cols = error.shape
    start = int(np.argmin(error[0]))
    cost = np.full(cols, np.inf)
    cost[start] = error[0, start]
    back = np.zeros((rows, cols), dtype=np.int64)
    index = np.arange(cols)
    for row in range(1, rows):
        left = np.concatenate(([np.inf], cost[:-1]))
        right = np.concatenate((cost[1:], [np.inf]))
        stacked = np.stack([left, cost, right])
        choice = np.argmin(stacked, axis=0)
        back[row] = index + choice - 1
        cost = stacked[choice, index] + error[row]
    path = np.empty(rows, dtype=np.int64)
    path[-1] = start
    for row in range(rows - 1, 0, -1):
        path[row - 1] = back[row, path[row]]
    return path


def _seam_mask(
    error: np.ndarray, centre: int, half_band: int, feather: float
) -> np.ndarray:
    """Weight (0..1) along columns: 1 between two loop cuts around column ``centre``.

    ``error`` is rows x cols; the left cut runs in ``[centre - half_band, centre - margin)``,
    the right one in ``[centre + margin, centre + half_band)``.
    """
    rows, cols = error.shape
    margin = int(np.ceil(3 * feather)) + 1  # keep the feathered cut off the seam itself
    left = (
        _loop_cut(error[:, centre - half_band : centre - margin]) + centre - half_band
    )
    right = _loop_cut(error[:, centre + margin : centre + half_band]) + centre + margin
    columns = np.arange(cols)[np.newaxis, :]
    mask = (
        (columns >= left[:, np.newaxis]) & (columns <= right[:, np.newaxis])
    ).astype(np.float64)
    if feather > 0:
        mask = gaussian_filter(mask, feather, mode="wrap")
    return mask


def make_seamless(
    image: np.ndarray, half_band: int, feather: float = 1.5
) -> np.ndarray:
    """Seamlessly tileable copy of ``image`` (H x W x 3 float) by min-error cuts.

    After a half-tile roll the original borders meet on a central cross. The vertical arm
    is replaced, between two minimum-error cuts, by a copy rolled on rows only (continuous
    across that arm), the horizontal arm by a copy rolled on columns only, and their
    crossing by the unrolled source. Cuts close on themselves so the result wraps.
    """
    height, width = image.shape[:2]
    if not 16 <= half_band < min(height, width) // 2:
        raise ValueError(f"demi-bande hors bornes : {half_band}")
    source = image.astype(np.float64)
    rolled_xy = np.roll(source, (height // 2, width // 2), axis=(0, 1))
    rolled_y = np.roll(source, height // 2, axis=0)
    rolled_x = np.roll(source, width // 2, axis=1)
    error_x = ((rolled_xy - rolled_y) ** 2).sum(axis=-1)
    weight_x = _seam_mask(error_x, width // 2, half_band, feather)
    error_y = (1 - weight_x) * ((rolled_xy - rolled_x) ** 2).sum(axis=-1) + weight_x * (
        (rolled_y - source) ** 2
    ).sum(axis=-1)
    weight_y = _seam_mask(error_y.T, height // 2, half_band, feather).T
    wx = weight_x[..., np.newaxis]
    wy = weight_y[..., np.newaxis]
    return (
        rolled_xy * (1 - wx) * (1 - wy)
        + rolled_y * wx * (1 - wy)
        + rolled_x * (1 - wx) * wy
        + source * wx * wy
    )


def low_pass(values: np.ndarray, sigma: float, mode: str) -> np.ndarray:
    """Wide Gaussian blur of a H x W (x C) image, computed at reduced resolution.

    The image is block-averaged by ``factor`` (sigma / 4, power of two), blurred there and
    brought back by linear interpolation: a sigma of ~150 px costs milliseconds.
    """
    from scipy.ndimage import zoom

    height, width = values.shape[:2]
    factor = 1
    while (
        factor * 2 <= sigma / 4
        and height % (factor * 2) == 0
        and width % (factor * 2) == 0
    ):
        factor *= 2
    extra = values.shape[2:]
    small = values.reshape(
        height // factor, factor, width // factor, factor, *extra
    ).mean(axis=(1, 3))
    sigmas = (sigma / factor, sigma / factor) + (0,) * len(extra)
    small = gaussian_filter(small, sigmas, mode=mode)
    if factor == 1:
        return small
    zoom_mode = "grid-wrap" if mode == "wrap" else "nearest"
    factors = (factor, factor) + (1,) * len(extra)
    return zoom(small, factors, order=1, mode=zoom_mode, grid_mode=True)


def flatten_lighting(
    linear: np.ndarray, sigma: float, strength: float = 0.7
) -> np.ndarray:
    """Divide out large-scale luminance variation (wrap-around blur), keeping chroma."""
    luminance = linear @ _LUMA
    low = low_pass(luminance, sigma, "wrap")
    ratio = (low.mean() / np.maximum(low, 1e-4)) ** strength
    return linear * ratio[..., np.newaxis]


def flatten_gradients(linear: np.ndarray, sigma: float) -> np.ndarray:
    """Remove large-scale colour gradients of a non-tiling image (vignetting, haze).

    Each channel is divided by its own mirrored-edge blur (times its mean), so the regions
    the seam cuts bring together share the same low-frequency colour and the cuts leave no
    visible band.
    """
    low = low_pass(linear, sigma, "reflect")
    means = linear.reshape(-1, linear.shape[-1]).mean(axis=0)
    return linear * (means / np.maximum(low, 1e-4))


def equalize_luminance(linear: np.ndarray, target: float) -> np.ndarray:
    """Scale linear RGB so its mean luminance equals ``target``."""
    mean = float((linear @ _LUMA).mean())
    return np.clip(linear * (target / max(mean, 1e-4)), 0.0, 1.0)


def derive_normal_rough(
    linear: np.ndarray, strength: float, base_roughness: float
) -> np.ndarray:
    """Normal (R, G, OpenGL) + roughness (B) from the high-passed luminance, uint8."""
    luminance = linear @ _LUMA
    height = luminance - gaussian_filter(luminance, 8.0, mode="wrap")
    height = gaussian_filter(height, 0.8, mode="wrap")
    scale = max(float(np.percentile(np.abs(height), 98)), 1e-5)
    height = np.clip(height / scale, -1.0, 1.0)
    dx = (np.roll(height, -1, axis=1) - np.roll(height, 1, axis=1)) * 0.5
    dy = (np.roll(height, -1, axis=0) - np.roll(height, 1, axis=0)) * 0.5
    nx, ny = -dx * strength, dy * strength  # OpenGL: +Y up, image rows go down
    nz = np.ones_like(nx)
    norm = np.sqrt(nx * nx + ny * ny + nz * nz)
    rough = np.clip(base_roughness + 0.1 * (-height), 0.0, 1.0)
    packed = np.stack([nx / norm * 0.5 + 0.5, ny / norm * 0.5 + 0.5, rough], axis=-1)
    return np.clip(np.rint(packed * 255), 0, 255).astype(np.uint8)


def seam_ratio(image: np.ndarray) -> float:
    """Wrap seam jump relative to the typical jump between neighbouring pixels.

    ~1 means the seam is as smooth as the texture interior; a hard seam scores several.
    """
    data = image.astype(np.float64)
    interior = np.concatenate(
        [np.abs(np.diff(data, axis=0)).ravel(), np.abs(np.diff(data, axis=1)).ravel()]
    ).mean()
    wrap = np.concatenate(
        [np.abs(data[0] - data[-1]).ravel(), np.abs(data[:, 0] - data[:, -1]).ravel()]
    ).mean()
    return float(wrap / max(interior, 1e-6))


def blotch_score(image: np.ndarray, blocks: int = 4) -> float:
    """Coefficient of variation of block-mean luminances (a dominant blotch scores high)."""
    luminance = image.astype(np.float64)
    if luminance.ndim == 3:
        luminance = luminance[..., :3] @ _LUMA
    size = luminance.shape[0] // blocks
    means = (
        luminance[: size * blocks, : size * blocks]
        .reshape(blocks, size, blocks, size)
        .mean(axis=(1, 3))
    )
    return float(means.std() / max(means.mean(), 1e-6))


def process(
    document: dict[str, Any], entry: dict[str, Any], raw_dir: Path = RAW_DIR
) -> dict[str, Any]:
    """Raw image -> tileable albedo + normal/roughness tiles in ``raw_dir/tiles``."""
    number = entry.get("attempt", 1)
    source = Image.open(raw_path(entry, number, raw_dir)).convert("RGB")
    size = document["layer_size"]
    linear = _srgb_to_linear(np.asarray(source, dtype=np.float64) / 255.0)
    scale = source.width / 1024
    linear = flatten_gradients(linear, sigma=source.width / 6)
    tiled = make_seamless(linear, int(document["blend_width"] * scale))
    tiled = flatten_lighting(tiled, sigma=source.width / 8)
    tiled = equalize_luminance(tiled, document["target_luminance"])
    albedo = Image.fromarray(
        np.clip(np.rint(_linear_to_srgb(tiled) * 255), 0, 255).astype(np.uint8)
    )
    if albedo.width != size:
        albedo = albedo.resize((size, size), Image.Resampling.LANCZOS)
    albedo_u8 = np.asarray(albedo)
    linear_out = _srgb_to_linear(albedo_u8 / 255.0)
    normal = derive_normal_rough(
        linear_out,
        entry.get("height_strength", DEFAULT_HEIGHT_STRENGTH),
        ROLE_ROUGHNESS[entry["role"]],
    )
    tiles = raw_dir / "tiles"
    tiles.mkdir(parents=True, exist_ok=True)
    albedo.save(tiles / f"{entry['id']}_albedo.png")
    Image.fromarray(normal).save(tiles / f"{entry['id']}_normal.png")
    return {
        "id": entry["id"],
        "seam_raw": round(seam_ratio(np.asarray(source)), 2),
        "seam": round(seam_ratio(albedo_u8), 2),
        "blotch": round(blotch_score(albedo_u8), 3),
        "mean_linear": [round(float(v), 4) for v in linear_out.reshape(-1, 3).mean(0)],
    }


def seamless(
    document: dict[str, Any], only: list[str] | None = None, raw_dir: Path = RAW_DIR
) -> list[dict[str, Any]]:
    """Process every selected material whose raw image exists; writes ``tiles/report.json``."""
    report_path = raw_dir / "tiles" / "report.json"
    previous = json.loads(report_path.read_text()) if report_path.exists() else {}
    rows = []
    for entry in select(document, only):
        if not raw_path(entry, entry.get("attempt", 1), raw_dir).exists():
            print(f"HB2 {entry['id']} : image brute absente, ignorée")
            continue
        row = process(document, entry, raw_dir)
        previous[entry["id"]] = row
        rows.append(row)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(previous, indent=1))
    return rows


# ------------------------------------------------------------------ packing
def grid_shape(count: int) -> tuple[int, int]:
    """(columns, rows) with columns * rows == count, as square as possible, <= 16 k px."""
    columns = max(c for c in range(1, int(np.sqrt(count)) + 1) if count % c == 0)
    return columns, count // columns


def import_file(columns: int, rows: int, source: str) -> str:
    """Godot ``.import`` of a grid image as a VRAM-compressed Texture2DArray (as GA4)."""
    return f"""[remap]

importer="2d_array_texture"
type="CompressedTexture2DArray"

[deps]

source_file="{RES_DIR}{source}"

[params]

compress/mode=2
compress/high_quality=false
compress/lossy_quality=0.7
compress/uastc_level=0
compress/rdo_quality_loss=0.0
compress/hdr_compression=1
compress/channel_pack=0
mipmaps/generate=true
mipmaps/limit=-1
slices/horizontal={columns}
slices/vertical={rows}
"""


def _resize_normal(normal: Image.Image, size: int) -> Image.Image:
    """Downsample a normal + roughness tile, renormalising the XY normal."""
    small = (
        np.asarray(normal.resize((size, size), Image.Resampling.BOX), dtype=np.float64)
        / 255.0
    )
    xy = small[..., :2] * 2 - 1
    length = np.sqrt((xy**2).sum(-1) + np.clip(1 - (xy**2).sum(-1), 0, 1))
    small[..., :2] = xy / np.maximum(length, 1e-6)[..., np.newaxis] * 0.5 + 0.5
    return Image.fromarray(np.clip(np.rint(small * 255), 0, 255).astype(np.uint8))


def pack(
    document: dict[str, Any],
    raw_dir: Path = RAW_DIR,
    texture_dir: Path = TEXTURE_DIR,
    manifest_path: Path = MANIFEST_PATH,
) -> dict[str, Any]:
    """Assemble the tiles into the two grid images, their imports and the manifest."""
    materials = document["materials"]
    size = document["layer_size"]
    normal_size = document.get("normal_size", size)
    columns, rows = grid_shape(len(materials))
    albedo_grid = Image.new("RGB", (columns * size, rows * size))
    normal_grid = Image.new("RGB", (columns * normal_size, rows * normal_size))
    layers = []
    tiles = raw_dir / "tiles"
    for entry in materials:
        albedo = Image.open(tiles / f"{entry['id']}_albedo.png").convert("RGB")
        normal = Image.open(tiles / f"{entry['id']}_normal.png").convert("RGB")
        if albedo.size != (size, size) or normal.size != (size, size):
            raise ValueError(
                f"{entry['id']} : tuile de taille {albedo.size}, {size}² attendu"
            )
        column, row = entry["layer"] % columns, entry["layer"] // columns
        albedo_grid.paste(albedo, (column * size, row * size))
        if normal_size != size:
            normal = _resize_normal(normal, normal_size)
        normal_grid.paste(normal, (column * normal_size, row * normal_size))
        mean = _srgb_to_linear(np.asarray(albedo, dtype=np.float64) / 255.0)
        layers.append(
            {
                "id": entry["id"],
                "layer": entry["layer"],
                "role": entry["role"],
                "biomes": entry["biomes"],
                "tile_m": entry["tile_m"],
                "mean_linear": [
                    round(float(v), 4) for v in mean.reshape(-1, 3).mean(0)
                ],
            }
        )
    texture_dir.mkdir(parents=True, exist_ok=True)
    albedo_path = texture_dir / ALBEDO_NAME
    normal_path = texture_dir / NORMAL_NAME
    albedo_grid.save(albedo_path, quality=ALBEDO_QUALITY, subsampling=0)
    normal_grid.save(normal_path, quality=NORMAL_QUALITY, subsampling=0)
    for path in (albedo_path, normal_path):
        imported = Path(f"{path}.import")
        slicing = f"slices/horizontal={columns}\nslices/vertical={rows}"
        # Keep Godot's own .import (uid, imported paths) while the grid is unchanged.
        if not imported.exists() or slicing not in imported.read_text():
            imported.write_text(import_file(columns, rows, path.name))
    total = albedo_path.stat().st_size + normal_path.stat().st_size
    if total > MAX_PACK_BYTES:
        raise ValueError(f"tableaux trop lourds : {total / 1e6:.1f} Mo > 40 Mo")
    manifest = {
        "layer_size": size,
        "normal_size": normal_size,
        "grid": [columns, rows],
        "albedo": RES_DIR + ALBEDO_NAME,
        "normal": RES_DIR + NORMAL_NAME,
        "layers": layers,
    }
    manifest_path.write_text(json.dumps(manifest, indent=1, ensure_ascii=False) + "\n")
    return {"grid": [columns, rows], "bytes": total, "layers": len(layers)}


# ------------------------------------------------------------------ review sheet
def _font(size: int) -> ImageFont.ImageFont | ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", size)
    except OSError:
        return ImageFont.load_default()


def board(document: dict[str, Any], raw_dir: Path = RAW_DIR, cell: int = 512) -> Path:
    """Review sheet: each albedo tile repeated 2 x 2 (seams at the cell centre lines)."""
    materials = document["materials"]
    columns = 6
    rows = -(-len(materials) // columns)
    sheet = Image.new("RGB", (columns * cell, rows * (cell + 28)), (30, 30, 30))
    draw = ImageDraw.Draw(sheet)
    font = _font(20)
    for index, entry in enumerate(materials):
        path = raw_dir / "tiles" / f"{entry['id']}_albedo.png"
        if not path.exists():
            continue
        tile = Image.open(path).convert("RGB").resize((cell // 2, cell // 2))
        x, y = index % columns * cell, index // columns * (cell + 28)
        for dx in (0, cell // 2):
            for dy in (0, cell // 2):
                sheet.paste(tile, (x + dx, y + 28 + dy))
        draw.text(
            (x + 6, y + 3), f"{entry['layer']} {entry['id']}", fill="white", font=font
        )
    target = raw_dir / "board_2x2.jpg"
    sheet.save(target, quality=85)
    return target
