"""HB2 (ADR 0143): ground materials of the campaign map generated by fal.ai.

Chain, driven by ``data/art/ground_materials.yaml``:

1. ``generate``: one nadir aerial orthophoto per material (``fal-ai/flux-2-pro`` 1024²,
   0.03 $/Mpx, catalogue price 2026-09-30) into ``~/dev/cent-ans-raw/hb/materials/``
   (``<id>_<attempt>.png``, never paid twice; every call logged in ``costs.json``).
2. ``seamless``: half-tile offset, then the two seam bands are replaced by min-error cuts
   (quilting-style dynamic programming) through copies that are continuous across each seam;
   large-scale lighting is flattened (wrap-around blur) so no blotch repeats at tile scale;
   mean linear luminance equalised to ``target_luminance`` (the colour map gives the hue);
   normal + roughness derived from the high-passed luminance (estimated height).
3. ``pack``: two grid images imported by Godot as ``CompressedTexture2DArray``
   (``hb_ground_albedo_array.jpg``, ``hb_ground_normal_array.jpg``: R, G = OpenGL normal X, Y,
   B = roughness, as ``terrain_normal_array.jpg``) + manifest
   ``data/art/ground_materials_pack.json`` (id -> layer, mean linear albedo).
4. ``board``: local review sheet, each texture tiled 2 x 2 (outside the repository).

Run: ``uv run --project tools --with fal-client cent-ans assets ground-materials generate``.
"""

from __future__ import annotations

import json
import time
import urllib.request
from pathlib import Path
from typing import Any

import numpy as np
import yaml
from PIL import Image

from cent_ans_tools.codex import schema_validator
from cent_ans_tools.paths import REPO_DIR as ROOT
from cent_ans_tools.texture_factory.board import board as factory_board
from cent_ans_tools.texture_factory.checks import blotch_score, seam_ratio
from cent_ans_tools.texture_factory.color import LUMA, linear_to_srgb, srgb_to_linear
from cent_ans_tools.texture_factory.pack import (  # noqa: F401  (re-exported)
    _resize_normal,
    grid_shape,
    import_file,
)
from cent_ans_tools.texture_factory.pack import pack as factory_pack
from cent_ans_tools.texture_factory.pbr import (
    derive_normal_rough,
    equalize_luminance,
    flatten_gradients,
    flatten_lighting,
)
from cent_ans_tools.texture_factory.seamless import (  # noqa: F401  (re-exported)
    _loop_cut,
    _seam_mask,
    low_pass,
    make_seamless,
)

CATALOG_PATH = ROOT / "data" / "art" / "ground_materials.yaml"
SCHEMA_PATH = ROOT / "data" / "schemas" / "ground_materials.schema.json"
MANIFEST_PATH = ROOT / "data" / "art" / "ground_materials_pack.json"
TEXTURE_DIR = ROOT / "game" / "assets" / "textures" / "terrain"
ALBEDO_NAME = "hb_ground_albedo_array.jpg"
NORMAL_NAME = "hb_ground_normal_array.jpg"
RES_DIR = "res://assets/textures/terrain/"
RAW_DIR = Path.home() / "dev" / "cent-ans-raw" / "hb" / "materials"

# Catalogue prices (USD per megapixel), fal pricing API 2026-09-30.
PRICES = {"fal-ai/flux-2-pro": 0.03, "fal-ai/flux-2": 0.012}
# Repository budget of the two arrays (spec: <= 40 MB).
MAX_PACK_BYTES = 40_000_000
ALBEDO_QUALITY = 88
NORMAL_QUALITY = 90
# Rec. 709 luma weights (linear RGB).
# Base roughness per role (matte crops, slightly glossier rock).
ROLE_ROUGHNESS = {"crop": 0.9, "canopy": 0.85, "ground": 0.8}
DEFAULT_HEIGHT_STRENGTH = 2.0


# ------------------------------------------------------------------ catalogue
def load_catalog(path: Path = CATALOG_PATH) -> dict[str, Any]:
    """Catalogue validated against its schema; layers must be 0..n-1 in order."""
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    validator = schema_validator(SCHEMA_PATH.parent.parent, SCHEMA_PATH.name)
    errors = list(validator.iter_errors(document))
    if errors:
        raise ValueError(f"{path.name} invalide : {errors[0].message}")
    ids = [m["id"] for m in document["materials"]]
    if len(ids) != len(set(ids)):
        raise ValueError("identifiants de matière en double")
    layers = [m["layer"] for m in document["materials"]]
    if layers != list(range(len(layers))):
        raise ValueError(f"couches non contiguës dans l'ordre : {layers}")
    return document


def build_prompt(
    document: dict[str, Any], entry: dict[str, Any], attempt: int = 1
) -> str:
    """Full prompt of ``entry`` (retry prompt for attempts >= 2 when given)."""
    body = entry["prompt"]
    if attempt >= 2 and entry.get("prompt_retry"):
        body = entry["prompt_retry"]
    scale = document["scale_sentence"].format(tile_m=entry["tile_m"])
    return " ".join(
        part.strip()
        for part in (document["style_prefix"], scale, body, document["style_suffix"])
        if part
    )


def raw_path(entry: dict[str, Any], attempt: int, raw_dir: Path = RAW_DIR) -> Path:
    """Raw generated image of ``entry`` for ``attempt``."""
    return raw_dir / f"{entry['id']}_{attempt}.png"


def call_cost(document: dict[str, Any]) -> float:
    """Catalogue cost of one generation (USD)."""
    megapixels = document["size"] * document["size"] / 1_000_000
    return round(PRICES[document["model"]] * megapixels, 4)


def select(document: dict[str, Any], only: list[str] | None) -> list[dict[str, Any]]:
    """Materials of the catalogue, restricted to ``only`` when given."""
    materials = document["materials"]
    if not only:
        return materials
    unknown = set(only) - {m["id"] for m in materials}
    if unknown:
        raise ValueError(f"matières inconnues : {sorted(unknown)}")
    return [m for m in materials if m["id"] in only]


# ------------------------------------------------------------------ generation
def generate(
    document: dict[str, Any],
    only: list[str] | None = None,
    attempt: int | None = None,
    dry_run: bool = False,
    raw_dir: Path = RAW_DIR,
    local: bool = False,
) -> dict[str, Any]:
    """Generate the missing raw images; returns ``{"planned": [...], "cost": usd}``.

    ``local`` renders each image with the free mflux model (1:1, same prompt and seed
    rule, no fal call, cost 0, ADR 0190).

    ``attempt`` None = the attempt kept by the catalogue (``attempt``, default 1).
    Attempt ``n`` uses seed ``seed + 1000 * (n - 1)``.
    """
    planned = []
    for entry in select(document, only):
        number = attempt or entry.get("attempt", 1)
        target = raw_path(entry, number, raw_dir)
        if not target.exists():
            planned.append((entry, number, target))
    unit = 0.0 if local else call_cost(document)
    report = {
        "planned": [f"{e['id']}_{n}" for e, n, _ in planned],
        "cost": round(unit * len(planned), 4),
    }
    if dry_run or not planned:
        return report
    if local:
        return _generate_local(document, planned, raw_dir, report)
    import fal_client  # only needed for paid calls

    raw_dir.mkdir(parents=True, exist_ok=True)
    log_path = raw_dir / "costs.json"
    log = json.loads(log_path.read_text()) if log_path.exists() else []
    for entry, number, target in planned:
        arguments = {
            "prompt": build_prompt(document, entry, number),
            "image_size": {"width": document["size"], "height": document["size"]},
            "seed": entry["seed"] + 1000 * (number - 1),
            "output_format": "png",
            "safety_tolerance": "5",
        }
        result = fal_client.subscribe(document["model"], arguments=arguments)
        urllib.request.urlretrieve(result["images"][0]["url"], target)
        (raw_dir / f"{target.stem}.json").write_text(
            json.dumps({"arguments": arguments, "result": result}, indent=1)
        )
        log.append(
            {
                "id": entry["id"],
                "attempt": number,
                "model": document["model"],
                "usd": unit,
                "time": time.strftime("%Y-%m-%dT%H:%M:%S"),
            }
        )
        log_path.write_text(json.dumps(log, indent=1))
        print(f"HB2 {target.name} ({unit} $)")
    return report


def _generate_local(
    document: dict[str, Any],
    planned: list[tuple[dict[str, Any], int, Path]],
    raw_dir: Path,
    report: dict[str, Any],
) -> dict[str, Any]:
    """Free local rendering of the planned raw images (no cost log, ADR 0190)."""
    from cent_ans_tools import local_art

    raw_dir.mkdir(parents=True, exist_ok=True)
    for entry, number, target in planned:
        image = local_art.render_image(
            build_prompt(document, entry, number),
            aspect_ratio="1:1",
            seed=entry["seed"] + 1000 * (number - 1),
        )
        target.write_bytes(image)
        print(f"HB2 {target.name} (local, 0 $)")
    return report


# ------------------------------------------------------------------ seamless
# Processing lives in the texture factory (TX T1b); names kept for HB callers.
_srgb_to_linear = srgb_to_linear
_linear_to_srgb = linear_to_srgb
_LUMA = LUMA


def process(
    document: dict[str, Any], entry: dict[str, Any], raw_dir: Path = RAW_DIR
) -> dict[str, Any]:
    """Raw image -> tileable albedo + normal/roughness tiles in ``raw_dir/tiles``."""
    number = entry.get("attempt", 1)
    source = Image.open(raw_path(entry, number, raw_dir)).convert("RGB")
    size = document["layer_size"]
    linear = _srgb_to_linear(np.asarray(source, dtype=np.float64) / 255.0)
    scale = source.width / 1024
    linear = flatten_gradients(linear, sigma=source.width / 6)
    tiled = make_seamless(linear, int(document["blend_width"] * scale))
    tiled = flatten_lighting(tiled, sigma=source.width / 8)
    tiled = equalize_luminance(tiled, document["target_luminance"])
    albedo = Image.fromarray(
        np.clip(np.rint(_linear_to_srgb(tiled) * 255), 0, 255).astype(np.uint8)
    )
    if albedo.width != size:
        albedo = albedo.resize((size, size), Image.Resampling.LANCZOS)
    albedo_u8 = np.asarray(albedo)
    linear_out = _srgb_to_linear(albedo_u8 / 255.0)
    normal = derive_normal_rough(
        linear_out,
        entry.get("height_strength", DEFAULT_HEIGHT_STRENGTH),
        ROLE_ROUGHNESS[entry["role"]],
    )
    tiles = raw_dir / "tiles"
    tiles.mkdir(parents=True, exist_ok=True)
    albedo.save(tiles / f"{entry['id']}_albedo.png")
    Image.fromarray(normal).save(tiles / f"{entry['id']}_normal.png")
    return {
        "id": entry["id"],
        "seam_raw": round(seam_ratio(np.asarray(source)), 2),
        "seam": round(seam_ratio(albedo_u8), 2),
        "blotch": round(blotch_score(albedo_u8), 3),
        "mean_linear": [round(float(v), 4) for v in linear_out.reshape(-1, 3).mean(0)],
    }


def seamless(
    document: dict[str, Any], only: list[str] | None = None, raw_dir: Path = RAW_DIR
) -> list[dict[str, Any]]:
    """Process every selected material whose raw image exists; writes ``tiles/report.json``."""
    report_path = raw_dir / "tiles" / "report.json"
    previous = json.loads(report_path.read_text()) if report_path.exists() else {}
    rows = []
    for entry in select(document, only):
        if not raw_path(entry, entry.get("attempt", 1), raw_dir).exists():
            print(f"HB2 {entry['id']} : image brute absente, ignorée")
            continue
        row = process(document, entry, raw_dir)
        previous[entry["id"]] = row
        rows.append(row)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(previous, indent=1))
    return rows


# ------------------------------------------------------------------ packing
def pack(
    document: dict[str, Any],
    raw_dir: Path = RAW_DIR,
    texture_dir: Path = TEXTURE_DIR,
    manifest_path: Path = MANIFEST_PATH,
) -> dict[str, Any]:
    """Assemble the tiles into the two grid images, their imports and the manifest."""
    return factory_pack(
        document,
        raw_dir,
        texture_dir,
        manifest_path,
        albedo_name=ALBEDO_NAME,
        normal_name=NORMAL_NAME,
        res_dir=RES_DIR,
        max_bytes=MAX_PACK_BYTES,
        albedo_quality=ALBEDO_QUALITY,
        normal_quality=NORMAL_QUALITY,
    )


# ------------------------------------------------------------------ review sheet
def board(document: dict[str, Any], raw_dir: Path = RAW_DIR, cell: int = 512) -> Path:
    """Review sheet: each albedo tile repeated 2 x 2 (seams at the cell centre lines)."""
    return factory_board(document, raw_dir, cell)
