"""Cap settlements at N per province (lot CO-A, ADR 0291).

``cent-ans geo settlement-cap`` rewrites ``data/settlements/prov_*.json`` so that a
province holds at most :data:`max_per_province` settlements (``data/map/settlement_cap_rules.json``):

* the province city is always kept;
* a settlement named by the ``protected_sources`` files (fleet ports, sea lanes, trade hubs,
  landmarks, crusade base, unrazable places...) is always kept;
* the other places are ranked by notability (weight, kind, port, fortification, test
  references), keeping at least one village and one famous castle or abbey when present;
* surviving minor towns are demoted to villages until villages >= ratio x towns (cities
  excluded); a demoted place loses the buildings and fortification the village kind forbids;
* removed settlements go to ``data/map/former_settlements.json`` (the hamlet generator
  merges them into ``hamlets.json``).

Files keyed by settlement id (fine anchors, town footprints, rank rules, bird towns) are
pruned here; the graph, positions and edge paths are regenerated by ``cent-ans geo
settlements`` and ``data/rules/starting_fit.json`` by the Rust test named in its description.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_DIR / "data"
RULES_PATH = DATA_DIR / "map" / "settlement_cap_rules.json"
FORMER_FILE = "former_settlements.json"
FORMER_DESCRIPTION = (
    "Colonies retirées par le plafond de cinq colonies par province (lot CO-A, ADR 0291). "
    "Ce ne sont plus des places de jeu : le générateur de hameaux (`cent-ans geo hamlets`) "
    "les fusionne dans hamlets.json, où elles restent des hameaux décoratifs non sélectionnables."
)
ID_PATTERN = re.compile(r"(?<![A-Za-z0-9_])set_[a-z0-9_]+")
# Directories never scanned for references.
SKIPPED_PARTS = {"target", ".git", ".godot", "node_modules"}


@dataclass
class CapPlan:
    """Outcome of :func:`plan`."""

    kept: dict[str, list[str]] = field(default_factory=dict)
    removed: list[dict] = field(default_factory=list)
    demoted: list[str] = field(default_factory=list)
    overflow: dict[str, int] = field(default_factory=dict)
    unreachable_ratio: bool = False


def load_rules(path: Path = RULES_PATH) -> dict:
    """The tuning file ``settlement_cap_rules.json``."""
    return json.loads(path.read_text(encoding="utf-8"))


def province_files(data_dir: Path = DATA_DIR) -> dict[str, Path]:
    """``prov_*.json`` settlement files by province id."""
    return {p.stem: p for p in sorted((data_dir / "settlements").glob("prov_*.json"))}


def load_all(data_dir: Path = DATA_DIR) -> dict[str, list[dict]]:
    """Settlement entries by province id, in file order."""
    return {
        pid: json.loads(path.read_text(encoding="utf-8"))
        for pid, path in province_files(data_dir).items()
    }


def referenced_ids(
    patterns: list[str], ids: set[str], repo_dir: Path = REPO_DIR
) -> set[str]:
    """Settlement ids mentioned in the files matching ``patterns`` (relative to the repo)."""
    found: set[str] = set()
    for pattern in patterns:
        for path in sorted(repo_dir.glob(pattern)):
            if not path.is_file() or SKIPPED_PARTS & set(path.parts):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            found.update(m for m in ID_PATTERN.findall(text) if m in ids)
    return found


def score(entry: dict, rules: dict, references: set[str]) -> float:
    """Notability of a settlement (higher keeps)."""
    value = float(entry["weight"])
    value += rules["kind_bonus"].get(entry["kind"], 0)
    value += rules["port_bonus"] if entry.get("port") else 0
    value += rules["sea_zone_bonus"] if entry.get("sea_zone") else 0
    value += rules["fortification_bonus_per_level"] * entry.get(
        "fortification_level", 0
    )
    value += rules["reference_bonus"] if entry["id"] in references else 0
    return value


def _best(entries: list[dict], key) -> dict | None:  # noqa: ANN001
    return max(entries, key=key) if entries else None


def select_province(
    entries: list[dict], rules: dict, protected: set[str], references: set[str]
) -> tuple[list[dict], int]:
    """Entries kept for one province (file order) and the count above the cap."""
    cap = rules["max_per_province"]

    def rank(entry: dict) -> tuple[float, str]:
        return (score(entry, rules, references), entry["id"])

    keep: dict[str, dict] = {e["id"]: e for e in entries if e["kind"] == "city"}
    keep.update({e["id"]: e for e in entries if e["id"] in protected})
    if len(entries) > cap:
        rest = [e for e in entries if e["id"] not in keep]
        needs_village = len(entries) >= rules["min_colonies_for_village"]
        if needs_village and not any(e["kind"] == "village" for e in keep.values()):
            pick = _best([e for e in rest if e["kind"] == "village"], rank)
            if pick and len(keep) < cap:
                keep[pick["id"]] = pick
        diverse = set(rules["diversity_kinds"])
        if not any(e["kind"] in diverse for e in keep.values()):
            pick = _best(
                [
                    e
                    for e in rest
                    if e["kind"] in diverse
                    and e["weight"] >= rules["diversity_min_weight"]
                    and e["id"] not in keep
                ],
                rank,
            )
            if pick and len(keep) < cap:
                keep[pick["id"]] = pick
        for entry in sorted(rest, key=rank, reverse=True):
            if len(keep) >= cap:
                break
            keep.setdefault(entry["id"], entry)
    else:
        keep = {e["id"]: e for e in entries}
    kept = [e for e in entries if e["id"] in keep]
    return kept, max(0, len(kept) - cap)


def plan(
    all_entries: dict[str, list[dict]],
    rules: dict,
    protected: set[str],
    references: set[str],
) -> CapPlan:
    """Choose the kept settlements and the demotions for the whole map."""
    result = CapPlan()
    survivors: dict[str, dict] = {}
    for province, entries in all_entries.items():
        kept, over = select_province(entries, rules, protected, references)
        result.kept[province] = [e["id"] for e in kept]
        if over:
            result.overflow[province] = over
        survivors.update({e["id"]: e for e in kept})
        kept_ids = {e["id"] for e in kept}
        result.removed += [e for e in entries if e["id"] not in kept_ids]

    demote = rules["demote"]
    towns = [e for e in survivors.values() if e["kind"] in demote["from_kinds"]]
    villages = sum(e["kind"] == demote["to_kind"] for e in survivors.values())
    candidates = sorted(
        (
            e
            for e in towns
            if not e.get("port")
            and not e.get("sea_zone")
            and e["id"] not in protected
            and e["weight"] < demote["keep_min_weight"]
        ),
        key=lambda e: (score(e, rules, references), e["id"]),
    )
    ratio = rules["village_ratio"]
    remaining = len(towns)
    for entry in candidates:
        if villages >= ratio * remaining:
            break
        result.demoted.append(entry["id"])
        villages += 1
        remaining -= 1
    result.unreachable_ratio = villages < ratio * remaining
    return result


def allowed_buildings(data_dir: Path = DATA_DIR) -> dict[str, set[str]]:
    """Settlement kinds allowed by each building (``settlement_kinds``; absent = all)."""
    allowed: dict[str, set[str]] = {}
    for path in sorted((data_dir / "buildings").glob("*.json")):
        entry = json.loads(path.read_text(encoding="utf-8"))
        allowed[entry["id"]] = set(entry.get("settlement_kinds", []))
    return allowed


def demote_entry(entry: dict, rules: dict, allowed: dict[str, set[str]]) -> dict:
    """The entry turned into the demotion kind: lower fortification, legal buildings only."""
    demote = rules["demote"]
    kind = demote["to_kind"]
    changed = dict(entry)
    changed["kind"] = kind
    changed["fortification_level"] = min(
        entry["fortification_level"], demote["village_max_fortification"]
    )
    changed["buildings"] = [
        b for b in entry["buildings"] if not allowed.get(b) or kind in allowed[b]
    ]
    return changed


def former_record(entry: dict) -> dict:
    """Entry of ``former_settlements.json``."""
    return {
        "id": entry["id"],
        "name": entry["name"]["display"],
        "province": entry["province"],
        "lonlat": entry["lonlat"],
        "former_kind": entry["kind"],
    }


def write_json(path: Path, value: object, indent: int | None = 2) -> None:
    """UTF-8 JSON with a trailing newline."""
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=indent) + "\n", encoding="utf-8"
    )


def prune_fine_anchors(former_ids: list[str], data_dir: Path = DATA_DIR) -> bool:
    """Move the fine anchors of the former settlements from ``settlements`` to ``hamlets``.

    Hamlet anchors follow ``hamlets.json`` order (GeoNames base, then the former settlements in
    ``former_settlements.json`` order, see ``geo/hamlets.py``). A former settlement without an
    anchor leaves a ``None`` row that ``hamlets.merge_former`` fills from the hamlet position.
    """
    path = data_dir / "map" / "fine_anchors.json"
    anchors = json.loads(path.read_text(encoding="utf-8"))
    present = anchors["settlements"]
    if not any(i in present for i in former_ids):
        return False
    rows = []
    for ident in former_ids:
        anchor = present.get(ident)
        rows.append(
            [anchor["px"][0], anchor["px"][1], anchor["z"], anchor.get("moved_m", 0.0)]
            if anchor
            else [None, None, None, 0.0]
        )
    anchors["hamlets"]["items"] += rows
    anchors["settlements"] = {
        k: v for k, v in present.items() if k not in set(former_ids)
    }
    path.write_text(
        json.dumps(anchors, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    return True


def prune_keyed_files(former_ids: list[str], data_dir: Path = DATA_DIR) -> list[str]:
    """Drop removed ids from the files keyed by settlement id; returns what changed.

    ``former_ids`` is the order of ``former_settlements.json`` (= hamlet order after the
    GeoNames base).
    """
    removed = set(former_ids)
    changed: list[str] = []
    map_dir = data_dir / "map"

    if prune_fine_anchors(former_ids, data_dir):
        changed.append("map/fine_anchors.json")

    towns_path = map_dir / "towns_1340.json"
    towns = json.loads(towns_path.read_text(encoding="utf-8"))
    if removed & set(towns["towns"]):
        towns["towns"] = {k: v for k, v in towns["towns"].items() if k not in removed}
        towns_path.write_text(
            json.dumps(towns, ensure_ascii=False, separators=(",", ":")) + "\n",
            encoding="utf-8",
        )
        changed.append("map/towns_1340.json")

    # One reference row per line: drop the rows of removed settlements, keep the layout.
    footprint_path = data_dir / "rules" / "town_footprint.json"
    lines = footprint_path.read_text(encoding="utf-8").split("\n")
    kept = [
        line
        for line in lines
        if not any(f'"settlement": "{ident}"' in line for ident in removed)
    ]
    if len(kept) != len(lines):
        footprint_path.write_text("\n".join(kept), encoding="utf-8")
        changed.append("rules/town_footprint.json")

    for name in ("settlement_markers.json", "map_birds.json"):
        path = map_dir / name
        document = json.loads(path.read_text(encoding="utf-8"))
        if _prune_ids(document, removed):
            path.write_text(
                json.dumps(document, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            changed.append(f"map/{name}")
    return changed


def _prune_ids(node: object, removed: set[str]) -> bool:
    """Remove removed ids from string lists, dict keys and ``{"settlement": id}`` rows, recursively."""
    touched = False
    if isinstance(node, dict):
        for key in [k for k in node if k in removed]:
            del node[key]
            touched = True
        for value in node.values():
            touched |= _prune_ids(value, removed)
    elif isinstance(node, list):
        kept = [
            x
            for x in node
            if not (isinstance(x, str) and x in removed)
            and not (isinstance(x, dict) and x.get("settlement") in removed)
        ]
        if len(kept) != len(node):
            node[:] = kept
            touched = True
        for value in node:
            touched |= _prune_ids(value, removed)
    return touched


def apply(
    data_dir: Path = DATA_DIR, repo_dir: Path = REPO_DIR, dry_run: bool = False
) -> tuple[CapPlan, dict[str, list[dict]]]:
    """Plan and (unless ``dry_run``) write the capped data."""
    rules = load_rules(data_dir / "map" / "settlement_cap_rules.json")
    all_entries = load_all(data_dir)
    ids = {e["id"] for entries in all_entries.values() for e in entries}
    protected = referenced_ids(rules["protected_sources"], ids, repo_dir)
    references = referenced_ids(rules["reference_sources"], ids, repo_dir)
    result = plan(all_entries, rules, protected, references)
    if dry_run:
        return result, all_entries
    allowed = allowed_buildings(data_dir)
    demoted = set(result.demoted)
    files = province_files(data_dir)
    for province, entries in all_entries.items():
        kept = [
            demote_entry(e, rules, allowed) if e["id"] in demoted else e
            for e in entries
            if e["id"] in set(result.kept[province])
        ]
        write_json(files[province], kept)
    if not result.removed:  # already capped: keep the existing former_settlements.json
        return result, all_entries
    former = sorted(
        (former_record(e) for e in result.removed),
        key=lambda r: (r["province"], r["id"]),
    )
    write_json(
        data_dir / "map" / FORMER_FILE,
        {"description": FORMER_DESCRIPTION, "settlements": former},
    )
    prune_keyed_files([r["id"] for r in former], data_dir)
    return result, all_entries
