"""One-shot migration of hand-written and pyramid-bound map-pixel data (lot OM2, ADR 0115).

The map grew from 4096² to 7168 x 6144 units with the same west edge and five
root tiles (1280 units) added above: a former map pixel ``(x, y)`` is now
``(x, y + 1280)``. Everything regenerated by ``cent-ans geo build`` (and the
sub-commands) is simply rebuilt; this module shifts the rest:

* ``data/landmarks/*.json``: ``anchor.px`` (written by hand from the geo tool);
* ``data/map/fine_anchors.json``: settlement, hamlet and crossing positions
  (the generator samples the relief pyramid, which is not recooked: see
  :func:`cent_ans_tools.geo.pyramid.require_world_frame`);
* ``data/map/towns_1340.json``: ``towns.*.px`` (same reason; every other
  coordinate of the file is local, in metres).

Data in lon/lat or ``origin_3035`` does not move. The game test and dev
scripts that aim at map points (``game/tests/*_shot.gd``...) were shifted by
hand in the same lot (list in ``docs/wip/om-om2.md``).

Run once: ``uv run --project tools python -m cent_ans_tools.geo.migrate_om2``.
Running it twice shifts twice: :func:`already_migrated` refuses a second run
(Paris' landmark anchor is the witness).
"""

from __future__ import annotations

import json
from pathlib import Path

from cent_ans_tools.geo.project import LEGACY_Y_OFFSET_PX

REPO_DIR = Path(__file__).resolve().parents[3]
DATA_DIR = REPO_DIR / "data"
#: Paris' landmark anchor on the former 4096² map (y), the witness of a migration.
PARIS_LEGACY_Y = 1924.516


def _shift(point: list[float], dy: float) -> list[float]:
    return [point[0], round(point[1] + dy, 4)]


def already_migrated(data_dir: Path = DATA_DIR) -> bool:
    """True when ``data/landmarks/paris.json`` already carries the shifted anchor."""
    path = data_dir / "landmarks" / "paris.json"
    if not path.exists():
        return False
    anchor = json.loads(path.read_text(encoding="utf-8"))["anchor"]["px"]
    return abs(anchor[1] - PARIS_LEGACY_Y) > 1.0


def migrate_landmarks(data_dir: Path, dy: float) -> list[Path]:
    """Shift ``anchor.px`` of every ``data/landmarks/*.json`` (text kept as is otherwise)."""
    changed = []
    for path in sorted((data_dir / "landmarks").glob("*.json")):
        text = path.read_text(encoding="utf-8")
        data = json.loads(text)
        old = data["anchor"]["px"]
        new = _shift(old, dy)
        needle = f'"px": [{old[0]}, {old[1]}]'
        if needle not in text:
            raise ValueError(f"{path}: anchor.px introuvable tel quel ({needle})")
        path.write_text(
            text.replace(needle, f'"px": [{new[0]}, {new[1]}]', 1), encoding="utf-8"
        )
        changed.append(path)
    return changed


def migrate_fine_anchors(path: Path, dy: float) -> None:
    """Shift settlement, hamlet and crossing positions of ``fine_anchors.json``."""
    data = json.loads(path.read_text(encoding="utf-8"))
    for entry in data["settlements"].values():
        entry["px"] = _shift(entry["px"], dy)
    y_index = data["hamlets"]["fields"].index("y")
    for item in data["hamlets"]["items"]:
        item[y_index] = round(item[y_index] + dy, 4)
    for crossing in data["crossings"]:
        crossing["px"] = _shift(crossing["px"], dy)
    data["description"] = data["description"].replace(
        "(pixels carte 4096)", "(pixels carte, ADR 0115)"
    )
    path.write_text(
        json.dumps(data, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )


def migrate_towns(path: Path, dy: float) -> None:
    """Shift ``towns.*.px`` of ``towns_1340.json``."""
    data = json.loads(path.read_text(encoding="utf-8"))
    for town in data["towns"].values():
        town["px"] = _shift(town["px"], dy)
    path.write_text(
        json.dumps(data, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )


def migrate(data_dir: Path = DATA_DIR, dy: float = LEGACY_Y_OFFSET_PX) -> list[Path]:
    """Apply every shift; returns the files written.

    Raises:
        RuntimeError: The data was already migrated.
    """
    if already_migrated(data_dir):
        raise RuntimeError("données déjà migrées (ancre de Paris déjà décalée)")
    written = migrate_landmarks(data_dir, dy)
    for name, step in (
        ("fine_anchors.json", migrate_fine_anchors),
        ("towns_1340.json", migrate_towns),
    ):
        path = data_dir / "map" / name
        if path.exists():
            step(path, dy)
            written.append(path)
    return written


if __name__ == "__main__":
    for written_path in migrate():
        print(written_path.relative_to(REPO_DIR))
